### PR TITLE
Mig repo merge

### PR DESCRIPTION
**Pull request by typekpb**
there was some activity in the original (mig's) repo, since the fork => merged

### CODE REVIEW

**Comment by ricardograca** [comment]
Seems like the only actual change is in the `zenburn` theme, so if you could get rid of all the extraneous commits and just provide a new commit with that change it would be great :)

I'm also looking at other branches that have changes in regards to `mig/gedit-themes` and possibly also implementing those changes here.

**Comment by typekpb** [comment]
Well, might be true, but merging this one  should lead to showing your repo
as having no commits behind original one. (At least I hope so) as it might
make people feel like your repo is not the actual one.

**Comment by ricardograca** [comment]
Ok, makes sense, but there isn't actually an "actual one" ever since mig stopped updating his. There are several forks and I try to keep up with changes, but I don't have much time to go over every single fork out there.

That said, I think this fork still has the best install script out there ;)

**Comment by ricardograca** [comment]
After looking at the change, I'm not too sure about it. It just changes the selection color to orange instead of the current green, but if I merge this the theme file will contain two conflicting rules for selection color and the style of the new rules doesn't match the styles of the other ones, where the `name` attribute is always the last in each rule.

Also, the new orange selection color doesn't seem to be part of the usual Zenburn color palette, so I'd prefer to keep it as it is.

**Comment by typekpb** [comment]
Your repo, your rules :) Feel free to ignore this one.

**Pull request closed without merging**
